turtlebot4_node:
  ros__parameters:
    wifi:
      interface: "wlp0s20f3"
      
      # Supported Functions:
      # Dock
      # Undock
      # Follow
      # Power
      # EStop

      # Menu Functions:
      # Scroll Up
      # Scroll Down
      # Back
      # Select
      # Help

      # Buttons:
      # create3_1
      # create3_power
      # create3_2
      # hmi_1
      # hmi_2
      # hmi_3
      # hmi_4

      # Format:
      # button: ["SHORT_PRESS_FUNC", "LONG_PRESS_FUNC", "LONG_PRESS_DURATION_MS"]

    buttons:  
      create3_1: ["Dock", "", ""]
      create3_power: ["EStop", "Power", "3000"]
      create3_2: ["Undock", "", ""]

      hmi_1: ["Select", "", ""]
      hmi_2: ["Back", "", ""]
      hmi_3: ["Scroll Up", "", ""]
      hmi_4: ["Scroll Down", "", ""]

      # Menu entry must match a function
    menu:
      entries: ["Dock", "Undock", "Power", "EStop", "Follow", "Help"]

